research_task:
  description: >
    Run vision tool on the image and extract the VIN number.
    Make sure extract the VIN number only
  expected_output: >
    17 digit string with letter and number
  agent: researcher

reporting_task:
  description: >
    Review the VIN number and describe the vehicle, including make, model and other information.
  expected_output: >
    A fully detail report about the vehicle
  agent: reporting_analyst
